first: commit
Rapid-Python/api-python-flask-pagination pull request #1
Opened 2022-08-22 11:44 UTC by reshmawaghmar

Please review the code for pagination in todo list.

2022-08-22 12:11 UTC, apoorv-nag requested changes

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +api = Blueprint('user', 'user')
what is the need of this line?

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +    print(request.form.get('add-todo'))
remove print lines and use the loggers to log into files

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +    return jsonify("task successfully added")
return the newly added model from API as JSON

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +@app.route('/get_all_task', methods=['GET'])
/get_all_task url can be better with the following endpoint
GET /task

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +def update_task(task_id):
endpoint should be 
PUT /task/<task_id>

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +    add_todo_db(request.form.get('name'))
create a constant for 'name' as it used on other places as well.

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +@app.route('/get_task/<task_id>', methods=['GET'])
URL should be
GET /task/:id

2022-08-22 12:11 UTC, apoorv-nag commented on app/controller/service_controller.py
> +    # todo_item['complete'] = True
remove the comments

2022-08-22 12:11 UTC, apoorv-nag commented on app/models/query_builder.py
> +def add_todo_db(name):
move all the query related logics to model or repositories.

2022-08-22 12:11 UTC, apoorv-nag commented on server.py
> +'''@app.route("/magazines")
what is this multiline comment for?

2022-08-22 12:11 UTC, apoorv-nag commented on server.py
> +def get_paginated_list(klass, url, start, limit):
klass or class?

2022-08-22 12:11 UTC, apoorv-nag commented on server.py
> +        obj['previous'] = url + '?start=%d&limit=%d' % (start_copy, limit_copy)
why are we creating URL in backend.
please explain the logic of this function.

2022-08-22 12:25 UTC, apoorv-nag commented on app/controller/service_controller.py
> +    print(request.form["name"])
use logger to log in files instead of standard output (consoles)

2022-08-25 11:20 UTC, reshmawaghmar commented on app/controller/service_controller.py
> +api = Blueprint('user', 'user')
changes done.

2022-09-09 07:38 UTC, merged